reb:
  scan_base_packages: com.codesky.reb

  mq:
    consumer:
      provider: com.codesky.reb.message.mq.impl.RocketMQConsumer
      uri: rocketmq://kk-dev-server:9876?group_id=reb_dev&orderly=yes&topicTags=test:*
