reb:
  scan_base_packages: com.codesky.reb
  proto_base_packages: com.codesky

  msg:
    security_key: LAxx8xCsB4pakW7o

  mq:
    consumer:
      provider: com.codesky.reb.message.mq.impl.RocketMQConsumer
      uri: rocketmq://kk-dev-server:9876?group_id=reb_dev&orderly=yes&batchMaxSize=2&topicTags=test:*

    producer:
      provider: com.codesky.reb.message.mq.impl.RocketMQProducer
      uri: rocketmq://kk-dev-server:9876?group_id=reb_default_producer_group&orderly=yes