
spring: {
   profiles: {
      active: 'dev',
   }
}

server: {
   port: 443,
   ssl: {
      key-alias: 'alias',
      key-store-type: 'PKCS12',
      key-store-password: 'oACI83Nn',
      key-store: 'file:./config/cert/8809337_test.uishare.com.pfx',
      enabled: true,
   }
}